### ISSUE TITLE
I/O pins

### ISSUE THREAD

**Issue by ghost** [jpcima/ysfx#12]
More on "everything is optional in jsfx"

- If Input/Output pins are not mentioned at all, reaper will read and show this as js in/out,
as long as there is `@sample` with something in it (and something can be anything)

![jsio](https://user-images.githubusercontent.com/80534683/142550766-370c30e5-2906-41a3-83fb-29c77a4873b4.png)

example fx:
https://bitbucket.org/kawaCat/reascript-m2bpack/src/master/JSFX%20effects/kawa_Simple_Mid_Side.jsfx
https://github.com/JoepVanlier/JSFX/blob/master/SatanVerb/SatanVerb.jsfx
also a file with nothing in it but 
```
@sample
hello
```
will have these I/O's

- If only input pins are mentioned reaper reads output as "unmapped" (which you would have to explicitly "zero out" in reaper)

![unmapped](https://user-images.githubusercontent.com/80534683/142550810-ee498bdf-3431-4001-ba1c-5fc0f2772e8e.png)
example fx: almost all in /Reaper/Effects/analysis/

- If only output pins are mentioned reaper will display this correctly 
but the effect still works...
(no example for this one, I just commented out the in pins of an EQ)

- And a completely empty file shows no I/O
but still compiles and passes audio (as long as it has a filename and sits in the Effects folder)

All above examples currently don't output sound when loaded in the YSFX-plugin.

**Comment by jpcima** [comment]
I/O should be fixed in 2307a50, please check

**Comment by mynameismuhl** [comment]
- "No I/O mentioned at all but `@sample` available" works.
- The analysis and metering still don't pass audio
Those are either no output mentioned or sometimes `out_pin:none`
- And empty file doesn't pass audio (but I don't know if you want that anyway)

**Comment by jpcima** [comment]
> The analysis and metering still don't pass audio

Are you sure this just doesn't relate to how Reaper connects things together?
these plugins show only with a pair of input pins.

The generic plugin of ysfx is not able of dynamic I/O ports, so it couldn't tell if whatever is loaded is input-only.

**Comment by mynameismuhl** [comment]
Its most likely reaper related.
I don't know if/how reajs handled those 
(freeware jsfx vst wrapper, not maintained anymore)
https://www.reaper.fm/reaplugs/
it s windows only. i don't have a windows set up at the moment so i cannot check that.
